### ISSUE TITLE
Error when initializing objects. 

### ISSUE THREAD

**Issue by Hunken100** [glandfried/TrueSkillThroughTime.R#1]
When i try to initialize objects like Player:

a1 <-  Player(Gaussian(0, 6), 1, 0.03)

I get the following error message: 

Error in initialize(value, ...) : 
  no slot of name "refMethods" for this object of class "classRepresentation"
  
 I use R version 4.1.2

**Comment by glandfried** [comment]
Hi!, 

I have tested it and I have had no problem.

![r412](https://user-images.githubusercontent.com/14896224/150847589-40c0faaa-6608-4ab0-91e4-6f0006ff007b.png)

Maybe you need to open the package first

```
library(TrueSkillThroughTime)
a1 <- Player(Gaussian(0, 6), 1, 0.03)
```

Provided it has been installed before

```
install.packages("TrueSkillThroughTime")
```
